[core]
log_file = "stderr"
log_mode = "dev"
max_cpus = "100%"

[http]
enabled_services = ["prometheussvc", "ocdavsvc", "datasvc"]
enabled_middlewares = ["cors", "log", "trace"]
network = "tcp"
address = "0.0.0.0:9998"

[http.middlewares.trace]
priority = 100
header = "x-trace"

[http.middlewares.log]
priority = 200

[http.middlewares.auth]
priority = 300
authsvc = "0.0.0.0:9999"
credential_strategy = "basic"
token_strategy = "header"
token_writer = "header"
token_manager = "jwt"

[http.handlers.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"

[http.handlers.auth.token_strategies.header]
header = "X-Access-Token"

[http.handlers.auth.token_writers.header]
header = "X-Access-Token"

[http.middlewares.cors]
priority = 400

[http.services.prometheussvc]
prefix = "metrics"

[http.services.iframeuisvc]
prefix = "iframe"

[http.services.webuisvc]
prefix = "ui"

[http.services.ocdavsvc]
prefix = "owncloud"
chunk_folder = "/var/tmp/owncloud/chunks"
storageprovidersvc = "localhost:9999"
enable_cors = true

[http.services.datasvc]
driver = "local"
prefix = "data"
temp_folder = "/var/tmp/"

[http.services.datasvc.drivers.eos]
mgm = "root://nowhere.org"
root_uid = 0
root_gid = 0

[http.services.datasvc.drivers.local]
root = "/var/tmp/owncloud/data"

[grpc]
network = "tcp"
address = "0.0.0.0:9999"
access_log = "stderr"
tls_enabled = true
tls_cert = "/etc/gridsecurity/host.cert"
tls_key = "/etc/gridsecurity/host.key"
enabled_services = ["storageprovidersvc", "authsvc", "storageregistrysvc", "appregistrysvc", "appprovidersvc"]
enabled_interceptors = ["auth", "prometheus", "log", "trace"]

[grpc.interceptors.recovery]
priority = 0

[grpc.interceptors.trace]
priority = 100
header = "x-trace"

[grpc.interceptors.log]
priority = 200

[grpc.interceptors.prometheus]
priority = 300

[grpc.interceptors.auth]
priority = 400
header = "x-access-token"
token_manager = "jwt"

[grpc.interceptors.auth.methods]
"/cs3.storageproviderv0alpha.StorageProviderService/Stat" = true

[grpc.interceptors.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"



[grpc.services.storageprovidersvc]
driver = "local"
mount_path = "/"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
data_server_url = "http://localhost:9998/data"

[grpc.services.storageprovidersvc.drivers.eos]
mgm = "root://nowhere.org"
root_uid = 0
root_gid = 0

[grpc.services.storageprovidersvc.drivers.local]
root = "/var/tmp/owncloud/data"

[grpc.services.authsvc]
auth_manager = "demo"
token_manager = "jwt"
user_manager = "demo"

[grpc.services.authsvc.token_managers.jwt]
secret = "Pive-Fumkiu4"

[grpc.services.storageregistrysvc]
driver = "static"

[grpc.services.storageregistrysvc.drivers.static.rules]
"/" = "localhost:9999"
"123e4567-e89b-12d3-a456-426655440000" = "localhost:9999"

[grpc.services.appregistrysvc]
driver = "static"

[grpc.services.appregistrysvc.static.rules]
".txt" = "localhost:9999"
"txt/plain" = "localhost:9999"

[grpc.services.appprovidersvc]
driver = "demo"

[grpc.services.appprovidersvc.demo]
iframe_ui_provider = "http://localhost:9998/iframeuisvc"
